#!/bin/bash
first_run=false
adb_check=""

starting_connected () {
    echo "ADBVNC:Device connected, setup ports forwarding..."
    logger "ADBVNC:Device connected, setup ports forwarding..."
    adb forward tcp:5901 tcp:5901
    adb reverse tcp:4712 tcp:4712
    adb reverse tcp:22222 tcp:22222
    echo "ADBVNC:Launching device chroot...."
    logger "ADBVNC:Launching device chroot...."
    adb shell su -c /data/local/bin/kavnc &
    sleep 3
    logger "ADBVNC:Start forwarding video and audio..."
    xinit /usr/bin/xtigervncviewer 127.0.0.1:1 -passwd /root/.vnc/passwd -Fullscreen -PreferredEncoding=Raw -AutoSelect=0
    sleep 3
}

terminated_connected () {
    echo -ne "Disconnect and reconnect device if you want to restart or 
1) shutdown Rockpi
2) terminate chroot on phone
3) exit ADBVNC
4) restart ADBVNC
Choose an option:  "
    read -r ans
    case $ans in
      1)
        echo "ADBVNC: Terminate chroot and shutdown system...."
        logger "ADBVNC: Terminate chroot shutdown system..."
        adb shell su -c killall kavnc
        adb shell su -c /data/local/bin/kakill
        sleep 1
        shutdown now -h
        exit 0
        ;;
      2)
        echo "ADBVNC: Terminate chroot..."
        logger "ADBVNC: Terminate chroot..."
        adb shell su -c killall kavnc
        adb shell su -c /data/local/bin/kakill
        sleep 1
        ;;
       3)
        exit 0
        ;;
      4)first_run=false;
        ;;
#        for backup voice:
#        echo "ADBVNC: starting backup..."
#        sleep 1
#        adb shell su -c "/data/adb/magisk/busybox tar -cvpz -f /sdcard/pidroid/kali_backup.tar.gz /data/local/kali"
#        adb shell su -c "cp -a /data/local/bin /sdcard/pidroid/"
#        adb pull -a /sdcard/pidroid /root/
#        ;;

    esac
}

terminated_disconnected () {
    echo "ADBVNC: Device disconnected or no chroot found, sleeping..."
    logger "ADBVNC: Device disconnected or no chroot found, sleeping..."
    echo "ADBVNC: Press CTL + C to terminate."
    sleep 3;
}




while true ; do
  clear;
  if (  ( adb get-state ) | grep "device"  > /dev/null 2>&1 )  &&  ( adb shell [ -d "/data/local/kali" ] )  ; then
    adb_check=$(adb devices -l | grep "device usb:")
    echo "ADBVNC: " $adb_check;
    if ( !($first_run) ) > /dev/null 2>&1; then
      first_run=true;
      starting_connected;
    else
      terminated_connected;
    fi
  else
    first_run=false;
    terminated_disconnected;
  fi
done
exit 0


